name: Java Spring CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Build with Maven
        run: mvn -B package --file pom.xml | tee maven-output.txt

      - name: Display Maven build output
        run: cat maven-output.txt

      - name: Run tests
        run: mvn test | tee test-output.txt

      - name: Display test results
        run: cat test-output.txt

      - name: List the current directory
        run: ls -a
